"""add max_daily_loss_usd

Revision ID: e42e0b52e4cf
Revises: cd1662e2b94e
Create Date: 2026-06-08 11:58:21.907953
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e42e0b52e4cf'
down_revision: Union[str, None] = 'cd1662e2b94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_daily_loss_usd', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_settings', schema=None) as batch_op:
        batch_op.drop_column('max_daily_loss_usd')

    # ### end Alembic commands ###
